// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';
import {context} from '../models';

export function AIChatCancel(arg1:string):Promise<void>;

export function AIChatSend(arg1:Array<ai.Message>,arg2:Array<ai.Tool>):Promise<Record<string, any>>;

export function AIChatStream(arg1:string,arg2:Array<ai.Message>,arg3:Array<ai.Tool>):Promise<void>;

export function AICheckSQL(arg1:string):Promise<ai.SafetyResult>;

export function AIDeleteProvider(arg1:string):Promise<void>;

export function AIGetActiveProvider():Promise<string>;

export function AIGetBuiltinPrompts():Promise<Record<string, string>>;

export function AIGetContextLevel():Promise<string>;

export function AIGetProviders():Promise<Array<ai.ProviderConfig>>;

export function AIGetSafetyLevel():Promise<string>;

export function AIListModels():Promise<Record<string, any>>;

export function AISaveProvider(arg1:ai.ProviderConfig):Promise<void>;

export function AISetActiveProvider(arg1:string):Promise<void>;

export function AISetContextLevel(arg1:string):Promise<void>;

export function AISetSafetyLevel(arg1:string):Promise<void>;

export function AITestProvider(arg1:ai.ProviderConfig):Promise<Record<string, any>>;

export function Startup(arg1:context.Context):Promise<void>;
